version: 2.1

jobs:
  print_workflow_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Print Circle CI Workflow ID
          command: echo $CIRCLE_WORKFLOW_ID
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  my_workflow:
    jobs:
      - print_workflow_id
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
